--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/NhanAZ/CustomJoinSound
build-by-default: true
branches:
- master
projects:
  CustomJoinSound:
    path: ""
    icon: icon.png
    lint:
      phpstan: false
...
