---
name: CustomJoinSound
version: 0.0.4
main: NhanAZ\CustomJoinSound\Main
api: 3.25.0
author: NhanAZ
website: https://github.com/NhanAZ
description: You will hear "Welcome to the server!" sound when joining the server
mcpe-protocol: 471
...
